version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: typeorm_postgres_db

    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=my_database

    volumes:
     - postgres:/var/lib/postgresql/data
volumes:
  postgres:
